export const environment =  {
    USER: process.env.ESPACIOS_ACADEMICOS_CRUD_USER,
    PASS: process.env.ESPACIOS_ACADEMICOS_CRUD_PASS,
    HOST: process.env.ESPACIOS_ACADEMICOS_CRUD_HOST,
    PORT: process.env.ESPACIOS_ACADEMICOS_CRUD_PORT,
    DB: process.env.ESPACIOS_ACADEMICOS_CRUD_DB,
    HTTP_PORT: process.env.ESPACIOS_ACADEMICOS_CRUD_HTTP_PORT,
    AUTH_DB: process.env.ESPACIOS_ACADEMICOS_CRUD_AUTH_DB 
};
